name: Update GitHub Profile RPG Stats

on:
  schedule:
    - cron: '0 0 * * *' # every day
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch GitHub Stats
        uses: jayrajroham/github-stats-readme@v1.0.0
        with:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "update RPG stats"
          git push
