name: Update GitHub Profile RPG Stats

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Run update-readme.js script
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_USERNAME: Seristic
        run: node update-readme.js

      - name: Commit & push updated README
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_USERNAME: Seristic
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:$PAT_TOKEN@github.com/$GITHUB_USERNAME/gamer-style-profile.git
          git add README.md
          git diff --cached --quiet || git commit -m "Update RPG stats"
          git push https://x-access-token:$PAT_TOKEN@github.com/$GITHUB_USERNAME/gamer-style-profile.git HEAD:master
