name: Generate Commit Runner Game

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate SVG
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          USERNAME: Seristic
        run: npm run generate

      - name: Commit and push SVG using PAT
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add runner-game.svg
          git commit -m "Update commit runner game SVG" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:master
