name: Update Profile Level

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run profile level updater
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_USERNAME: Seristic
          GITHUB_REPO: https://github.com/Seristic/Seristic
        run: node index.js

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add README.md progress.svg
          git diff --quiet && echo "No changes to commit" || (git commit -m "Update profile level and progress" && git push)
